# Generated by Django 5.1.5 on 2025-03-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='x_users',
        ),
    ]
